apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod-reader
spec:
  containers:
  - name: helm
    image: lachlanevenson/k8s-helm:v3.1.1
    command:
    - cat
  serviceAccountName: default     

